In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
demand_set=pd.read_csv('Demand_History.csv')

In [3]:
demand_set.head(3001)

demand_point_index  x_coordinate  y_coordinate      2010       2011  \
0                      0           0.5           0.5  0.352242   0.667932   
1                      1           1.5           0.5  0.325940   0.591964   
2                      2           2.5           0.5  0.373752   0.591890   
3                      3           3.5           0.5  0.420686   0.584055   
4                      4           4.5           0.5  0.475621   0.647940   
...                  ...           ...           ...       ...        ...   
2996                2996          52.5          46.5  4.625235  12.143628   
2997                2997          53.5          46.5  5.545604  12.060494   
2998                2998          54.5          46.5  4.529727  10.072652   
2999                2999          55.5          46.5  4.999517  10.839404   
3000                3000          56.5          46.5  5.566502  10.820340   

           2012       2013       2014        2015        2016        2017  \
0      0.958593   2.911901   4.338274    6.561995    8.454417   10.595324   
1      0.862652   2.589068   4.196034    5.745551    8.753195   11.126995   
2      0.969733   2.641432   3.541772    5.469161    8.414627   10.115336   
3      0.906547   2.378577   3.888121    5.846089    9.083868   12.424885   
4      0.981544   2.665400   4.218711    6.776609    8.851107   11.731131   
...         ...        ...        ...         ...         ...         ...   
2996  22.455179  52.032661  77.119005  113.836086  152.360672  230.095120   
2997  22.124514  51.883741  92.209896  118.386781  172.757477  253.187015   
2998  17.164560  57.496903  88.955036  112.158384  178.484338  245.780912   
2999  18.440202  51.605100  99.448430  128.168971  181.183438  258.521824   
3000  19.672903  53.307542  79.916763  124.790920  141.685324  209.325166   

            2018  
0      13.119572  
1      12.020091  
2      14.018254  
3      15.012302  
4      16.355563  
...          ...  
2996  224.158001  
2997  248.156533  
2998  237.367472  
2999  262.866348  
3000  250.105069  

[3001 rows x 12 columns]

In [4]:
X = np.array([[2010],[2011],[2012],[2013],[2014],[2015],[2016],[2017],[2018]])
X

array([[2010],
       [2011],
       [2012],
       [2013],
       [2014],
       [2015],
       [2016],
       [2017],
       [2018]])

In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [7]:
poly_reg3=PolynomialFeatures(degree=3)

x_poly_3=poly_reg3.fit_transform(X)

In [8]:
x_poly_3

array([[1.00000000e+00, 2.01000000e+03, 4.04010000e+06, 8.12060100e+09],
       [1.00000000e+00, 2.01100000e+03, 4.04412100e+06, 8.13272733e+09],
       [1.00000000e+00, 2.01200000e+03, 4.04814400e+06, 8.14486573e+09],
       [1.00000000e+00, 2.01300000e+03, 4.05216900e+06, 8.15701620e+09],
       [1.00000000e+00, 2.01400000e+03, 4.05619600e+06, 8.16917874e+09],
       [1.00000000e+00, 2.01500000e+03, 4.06022500e+06, 8.18135338e+09],
       [1.00000000e+00, 2.01600000e+03, 4.06425600e+06, 8.19354010e+09],
       [1.00000000e+00, 2.01700000e+03, 4.06828900e+06, 8.20573891e+09],
       [1.00000000e+00, 2.01800000e+03, 4.07232400e+06, 8.21794983e+09]])

In [9]:
ncol1=[]
ncol2=[]
for i in range(4096):
    y = demand_set.iloc[i,3:].values
    lin_reg_3=LinearRegression()
    lin_reg_3.fit(x_poly_3,y)
    ans1=lin_reg_3.predict(poly_reg3.transform([[2019]]))
    ans2=lin_reg_3.predict(poly_reg3.transform([[2020]]))
    ncol1.append(ans1[0])
    ncol2.append(ans2[0])

In [10]:
demand_set['2019']=ncol1
demand_set['2020']=ncol2

In [11]:
demand_set

demand_point_index  x_coordinate  y_coordinate      2010      2011  \
0                      0           0.5           0.5  0.352242  0.667932   
1                      1           1.5           0.5  0.325940  0.591964   
2                      2           2.5           0.5  0.373752  0.591890   
3                      3           3.5           0.5  0.420686  0.584055   
4                      4           4.5           0.5  0.475621  0.647940   
...                  ...           ...           ...       ...       ...   
4091                4091          59.5          63.5  0.171015  0.334565   
4092                4092          60.5          63.5  0.041716  0.061741   
4093                4093          61.5          63.5  0.100895  0.180352   
4094                4094          62.5          63.5  0.155353  0.290825   
4095                4095          63.5          63.5  0.209372  0.340185   

          2012      2013      2014      2015      2016       2017       2018  \
0     0.958593  2.911901  4.338274  6.561995  8.454417  10.595324  13.119572   
1     0.862652  2.589068  4.196034  5.745551  8.753195  11.126995  12.020091   
2     0.969733  2.641432  3.541772  5.469161  8.414627  10.115336  14.018254   
3     0.906547  2.378577  3.888121  5.846089  9.083868  12.424885  15.012302   
4     0.981544  2.665400  4.218711  6.776609  8.851107  11.731131  16.355563   
...        ...       ...       ...       ...       ...        ...        ...   
4091  0.556055  1.373291  1.837586  2.517146  3.352280   4.149888   5.426193   
4092  0.131291  0.386540  0.755846  0.941116  1.107797   1.309479   2.057450   
4093  0.296299  0.705373  1.300220  1.608609  1.822806   2.333681   3.218519   
4094  0.557803  1.516066  2.399426  2.719197  4.494515   6.096858   6.262574   
4095  0.749491  1.904285  2.775772  3.404641  4.574922   6.301078   6.860939   

           2019       2020  
0     15.088540  16.926841  
1     13.453829  13.834499  
2     17.501605  21.635356  
3     18.674598  22.182949  
4     20.526166  25.621623  
...         ...        ...  
4091   6.540436   7.850612  
4092   2.459605   3.065246  
4093   3.785937   4.543370  
4094   7.283772   7.752377  
4095   7.938740   8.711581  

[4096 rows x 14 columns]

In [12]:
#demand_set.to_excel('Prediction.xlsx')

In [13]:
arr=demand_set['2018']>demand_set['2019']

In [14]:
un,co=np.unique(arr,return_counts=True)

In [15]:
un

array([False,  True])

In [16]:
co

array([4007,   89], dtype=int64)

In [17]:
sum(arr)

89

In [18]:
arr_i=[]
for i in range(4096):
    if arr[i]==True:
        arr_i.append(i)
arr_i

[255,
 674,
 747,
 803,
 827,
 991,
 1151,
 1299,
 1327,
 1423,
 1429,
 1496,
 1914,
 2070,
 2078,
 2079,
 2142,
 2154,
 2298,
 2394,
 2395,
 2457,
 2458,
 2466,
 2467,
 2521,
 2522,
 2523,
 2527,
 2532,
 2533,
 2585,
 2589,
 2591,
 2594,
 2649,
 2654,
 2656,
 2659,
 2721,
 2783,
 2846,
 2848,
 2912,
 3037,
 3038,
 3070,
 3098,
 3101,
 3159,
 3160,
 3161,
 3166,
 3176,
 3177,
 3290,
 3344,
 3353,
 3356,
 3367,
 3598,
 3615,
 3618,
 3679,
 3680,
 3742,
 3745,
 3806,
 3807,
 3808,
 3810,
 3812,
 3870,
 3872,
 3877,
 3934,
 3935,
 3941,
 3948,
 3999,
 4005,
 4006,
 4013,
 4014,
 4015,
 4063,
 4069,
 4070,
 4078]

In [19]:
len(arr_i)

89