In [1]:
import numpy as np
import pandas as pd

In [2]:
demand_history=pd.read_csv('Demand_History.csv')
demand_history

demand_point_index  x_coordinate  y_coordinate      2010      2011  \
0                      0           0.5           0.5  0.352242  0.667932   
1                      1           1.5           0.5  0.325940  0.591964   
2                      2           2.5           0.5  0.373752  0.591890   
3                      3           3.5           0.5  0.420686  0.584055   
4                      4           4.5           0.5  0.475621  0.647940   
...                  ...           ...           ...       ...       ...   
4091                4091          59.5          63.5  0.171015  0.334565   
4092                4092          60.5          63.5  0.041716  0.061741   
4093                4093          61.5          63.5  0.100895  0.180352   
4094                4094          62.5          63.5  0.155353  0.290825   
4095                4095          63.5          63.5  0.209372  0.340185   

          2012      2013      2014      2015      2016       2017       2018  
0     0.958593  2.911901  4.338274  6.561995  8.454417  10.595324  13.119572  
1     0.862652  2.589068  4.196034  5.745551  8.753195  11.126995  12.020091  
2     0.969733  2.641432  3.541772  5.469161  8.414627  10.115336  14.018254  
3     0.906547  2.378577  3.888121  5.846089  9.083868  12.424885  15.012302  
4     0.981544  2.665400  4.218711  6.776609  8.851107  11.731131  16.355563  
...        ...       ...       ...       ...       ...        ...        ...  
4091  0.556055  1.373291  1.837586  2.517146  3.352280   4.149888   5.426193  
4092  0.131291  0.386540  0.755846  0.941116  1.107797   1.309479   2.057450  
4093  0.296299  0.705373  1.300220  1.608609  1.822806   2.333681   3.218519  
4094  0.557803  1.516066  2.399426  2.719197  4.494515   6.096858   6.262574  
4095  0.749491  1.904285  2.775772  3.404641  4.574922   6.301078   6.860939  

[4096 rows x 12 columns]

In [3]:
n_demand=demand_history.shape[0]

In [4]:
x1 = np.array([[2010],[2011],[2012],[2013],[2014],[2015],[2016],[2017],[2018]])
x2 = np.array([[2010],[2011],[2012],[2013],[2014],[2015],[2016],[2017],[2018],[2019]])
print(x1)
print(x2)

[[2010]
 [2011]
 [2012]
 [2013]
 [2014]
 [2015]
 [2016]
 [2017]
 [2018]]
[[2010]
 [2011]
 [2012]
 [2013]
 [2014]
 [2015]
 [2016]
 [2017]
 [2018]
 [2019]]


In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
lin_reg=LinearRegression()

In [6]:
poly_reg=PolynomialFeatures(degree=3)
x_poly1=poly_reg.fit_transform(x1)
x_poly2=poly_reg.fit_transform(x2)
print(x_poly1)
print(x_poly2)

[[1.00000000e+00 2.01000000e+03 4.04010000e+06 8.12060100e+09]
 [1.00000000e+00 2.01100000e+03 4.04412100e+06 8.13272733e+09]
 [1.00000000e+00 2.01200000e+03 4.04814400e+06 8.14486573e+09]
 [1.00000000e+00 2.01300000e+03 4.05216900e+06 8.15701620e+09]
 [1.00000000e+00 2.01400000e+03 4.05619600e+06 8.16917874e+09]
 [1.00000000e+00 2.01500000e+03 4.06022500e+06 8.18135338e+09]
 [1.00000000e+00 2.01600000e+03 4.06425600e+06 8.19354010e+09]
 [1.00000000e+00 2.01700000e+03 4.06828900e+06 8.20573891e+09]
 [1.00000000e+00 2.01800000e+03 4.07232400e+06 8.21794983e+09]]
[[1.00000000e+00 2.01000000e+03 4.04010000e+06 8.12060100e+09]
 [1.00000000e+00 2.01100000e+03 4.04412100e+06 8.13272733e+09]
 [1.00000000e+00 2.01200000e+03 4.04814400e+06 8.14486573e+09]
 [1.00000000e+00 2.01300000e+03 4.05216900e+06 8.15701620e+09]
 [1.00000000e+00 2.01400000e+03 4.05619600e+06 8.16917874e+09]
 [1.00000000e+00 2.01500000e+03 4.06022500e+06 8.18135338e+09]
 [1.00000000e+00 2.01600000e+03 4.06425600e+06 8.19354

In [7]:
y_test1=poly_reg.transform([[2019]])
y_test2=poly_reg.transform([[2020]])
print(y_test1)
print(y_test2)

[[1.00000000e+00 2.01900000e+03 4.07636100e+06 8.23017286e+09]]
[[1.000000e+00 2.020000e+03 4.080400e+06 8.242408e+09]]


In [8]:
col19=[]
for i in range(n_demand):
    y = demand_history.iloc[i,3:].values
    lin_reg.fit(x_poly1,y)
    ans=lin_reg.predict(y_test1)
    col19.append(ans[0])

In [9]:
demand_history['2019']=col19
demand_history

demand_point_index  x_coordinate  y_coordinate      2010      2011  \
0                      0           0.5           0.5  0.352242  0.667932   
1                      1           1.5           0.5  0.325940  0.591964   
2                      2           2.5           0.5  0.373752  0.591890   
3                      3           3.5           0.5  0.420686  0.584055   
4                      4           4.5           0.5  0.475621  0.647940   
...                  ...           ...           ...       ...       ...   
4091                4091          59.5          63.5  0.171015  0.334565   
4092                4092          60.5          63.5  0.041716  0.061741   
4093                4093          61.5          63.5  0.100895  0.180352   
4094                4094          62.5          63.5  0.155353  0.290825   
4095                4095          63.5          63.5  0.209372  0.340185   

          2012      2013      2014      2015      2016       2017       2018  \
0     0.958593  2.911901  4.338274  6.561995  8.454417  10.595324  13.119572   
1     0.862652  2.589068  4.196034  5.745551  8.753195  11.126995  12.020091   
2     0.969733  2.641432  3.541772  5.469161  8.414627  10.115336  14.018254   
3     0.906547  2.378577  3.888121  5.846089  9.083868  12.424885  15.012302   
4     0.981544  2.665400  4.218711  6.776609  8.851107  11.731131  16.355563   
...        ...       ...       ...       ...       ...        ...        ...   
4091  0.556055  1.373291  1.837586  2.517146  3.352280   4.149888   5.426193   
4092  0.131291  0.386540  0.755846  0.941116  1.107797   1.309479   2.057450   
4093  0.296299  0.705373  1.300220  1.608609  1.822806   2.333681   3.218519   
4094  0.557803  1.516066  2.399426  2.719197  4.494515   6.096858   6.262574   
4095  0.749491  1.904285  2.775772  3.404641  4.574922   6.301078   6.860939   

           2019  
0     15.088540  
1     13.453829  
2     17.501605  
3     18.674598  
4     20.526166  
...         ...  
4091   6.540436  
4092   2.459605  
4093   3.785937  
4094   7.283772  
4095   7.938740  

[4096 rows x 13 columns]

In [10]:
col20=[]
for i in range(n_demand):
    y = demand_history.iloc[i,3:].values
    lin_reg.fit(x_poly2,y)
    ans=lin_reg.predict(y_test2)
    col20.append(ans[0])

In [11]:
demand_history['2020']=col20
demand_history

demand_point_index  x_coordinate  y_coordinate      2010      2011  \
0                      0           0.5           0.5  0.352242  0.667932   
1                      1           1.5           0.5  0.325940  0.591964   
2                      2           2.5           0.5  0.373752  0.591890   
3                      3           3.5           0.5  0.420686  0.584055   
4                      4           4.5           0.5  0.475621  0.647940   
...                  ...           ...           ...       ...       ...   
4091                4091          59.5          63.5  0.171015  0.334565   
4092                4092          60.5          63.5  0.041716  0.061741   
4093                4093          61.5          63.5  0.100895  0.180352   
4094                4094          62.5          63.5  0.155353  0.290825   
4095                4095          63.5          63.5  0.209372  0.340185   

          2012      2013      2014      2015      2016       2017       2018  \
0     0.958593  2.911901  4.338274  6.561995  8.454417  10.595324  13.119572   
1     0.862652  2.589068  4.196034  5.745551  8.753195  11.126995  12.020091   
2     0.969733  2.641432  3.541772  5.469161  8.414627  10.115336  14.018254   
3     0.906547  2.378577  3.888121  5.846089  9.083868  12.424885  15.012302   
4     0.981544  2.665400  4.218711  6.776609  8.851107  11.731131  16.355563   
...        ...       ...       ...       ...       ...        ...        ...   
4091  0.556055  1.373291  1.837586  2.517146  3.352280   4.149888   5.426193   
4092  0.131291  0.386540  0.755846  0.941116  1.107797   1.309479   2.057450   
4093  0.296299  0.705373  1.300220  1.608609  1.822806   2.333681   3.218519   
4094  0.557803  1.516066  2.399426  2.719197  4.494515   6.096858   6.262574   
4095  0.749491  1.904285  2.775772  3.404641  4.574922   6.301078   6.860939   

           2019       2020  
0     15.088540  16.925371  
1     13.453829  13.827596  
2     17.501605  21.635659  
3     18.674598  22.179762  
4     20.526166  25.623670  
...         ...        ...  
4091   6.540436   7.850964  
4092   2.459605   3.065697  
4093   3.785937   4.543876  
4094   7.283772   7.752700  
4095   7.938740   8.711124  

[4096 rows x 14 columns]

demand_history.to_csv('Demand_Predictions.csv',index=False)